spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod_db
    username: prod_user
    password: prod_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

logging:
  level:
    root: WARN
    org.springframework.web: ERROR