spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local_db
    username: local_user
    password: local_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true