spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stg_db
    username: stg_user
    password: stg_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false